Thunder/Models/Region.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thunder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Region()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int RegionId { get; set; }
        public string RegionName { get; set; }
        public string RegionDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}

Thunder/Controllers/RegionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Thunder.Models;

namespace Thunder.Controllers
{
    public class RegionsController : Controller
    {
        private ShoppingCartEntities db = new ShoppingCartEntities();

        // GET: Regions
        public ActionResult Index()
        {
            return View(db.Regions.ToList());
        }

        // GET: Regions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Region region = db.Regions.Find(id);
            if (region == null)
            {
                return HttpNotFound();
            }
            return View(region);
        }

        // GET: Regions/Create
        [ValidateInput(false)]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Regions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RegionId,RegionName,RegionDescription")] Region region)
        {
            if (ModelState.IsValid)
            {
                db.Regions.Add(region);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(region);
        }

        // GET: Regions/Edit/5
        [ValidateInput(false)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Region region = db.Regions.Find(id);
            if (region == null)
            {
                return HttpNotFound();
            }
            return View(region);
        }

        // POST: Regions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RegionId,RegionName,RegionDescription")] Region region)
        {
            if (ModelState.IsValid)
            {
                db.Entry(region).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(region);
        }

        // GET: Regions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Region region = db.Regions.Find(id);
            if (region == null)
            {
                return HttpNotFound();
            }
            return View(region);
        }

        // POST: Regions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Region region = db.Regions.Find(id);
            db.Regions.Remove(region);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Thunder/Views/Regions/Create.cshtml
@model Thunder.Models.Region

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2 class="text-center">Create Regions</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RegionName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegionDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegionDescription, new { htmlAttributes = new { @class = "form-control", @Id = "editor1" } })
                @Html.ValidationMessageFor(model => model.RegionDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-warning" aria-label="Left Align">
                    <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>
                </button>
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index", "Regions")" class="btn btn-default">
        <i class="	glyphicon glyphicon-sort-by-attributes"></i>
        <span>

        </span>
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
        CKEDITOR.replace('editor1');
</script>

}

Thunder/Views/Regions/Delete.cshtml
@model Thunder.Models.Region

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Region</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RegionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegionDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegionDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button type="submit" class="btn btn-danger" aria-label="Left Align">
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            </button> |
            <a href="@Url.Action("Index", "Regions")" class="btn btn-default">
                <i class="	glyphicon glyphicon-sort-by-attributes"></i>
                <span>

                </span>
            </a>
        </div>
    }
</div>

Thunder/Views/Regions/Details.cshtml
@model Thunder.Models.Region

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2 class="text-center">Details Regions</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RegionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegionDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegionDescription)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Edit", "Regions", new { id = Model.RegionId })" class="btn btn-default">
        <i class="glyphicon glyphicon-flash"></i>
        <span>

        </span>
    </a>
    |
    <a href="@Url.Action("Index", "Regions")" class="btn btn-default">
        <i class="	glyphicon glyphicon-sort-by-attributes"></i>
        <span>

        </span>
    </a>
</p>

Thunder/Views/Regions/Edit.cshtml
@model Thunder.Models.Region

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2 class="text-center">Edit Regions</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RegionId)

        <div class="form-group">
            @Html.LabelFor(model => model.RegionName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegionName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegionDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegionDescription, new { htmlAttributes = new { @class = "form-control", @Id = "editor1" } })
                @Html.ValidationMessageFor(model => model.RegionDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-success" aria-label="Left Align">
                    <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>
                </button>
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index", "Regions")" class="btn btn-default">
        <i class="	glyphicon glyphicon-sort-by-attributes"></i>
        <span>

        </span>
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
        CKEDITOR.replace('editor1');
</script>
}

Thunder/Views/Regions/Index.cshtml
@model IEnumerable<Thunder.Models.Region>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2 class="text-center"> Regions </h2>

<p>
    <a href="@Url.Action("Create", "Regions")" class="btn btn-info">
        <i class="	glyphicon glyphicon-floppy-saved"></i>
        <span>

        </span>
    </a>

</p>
<table class="table table-bordered table-striped table-responsive" id="datatablefill">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RegionName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegionDescription)
            </th>
            <th></th>
        </tr>
        </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RegionName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RegionDescription)
                </td>
                <td>
                    <a href="@Url.Action("Edit", "Regions", new { id = item.RegionId })" class="btn btn-success">
                        <i class="glyphicon glyphicon-flash"></i>
                        <span>

                        </span>
                    </a>
                   |
                    <a href="@Url.Action("Details", "Regions", new { id = item.RegionId })" class="btn btn-primary">
                        <i class="	glyphicon glyphicon-list-alt"></i>
                        <span>

                        </span>
                    </a>
                    |
                    <a href="@Url.Action("Delete", "Regions", new { id = item.RegionId })" class="btn btn-danger">
                        <i class="glyphicon glyphicon-trash"></i>
                        <span>

                        </span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>
@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatablefill').DataTable();


        });
    </script>
}